name: nodeseek鸡腿签到

on:
  push:
    branches:
      - main  # 在 main 分支上进行推送时触发
  schedule:
    - cron: '12 1 * * *'  # 每天凌晨 12 点执行

jobs:
  run-nodeseek-sign:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.8'

      - name: install
        run: pip install requests

      - name: run
        env:
          COOKIE: ${{ secrets.COOKIE }}
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python nodeseek_sign.py
